import type { Preset, LegwearOption } from './types';

export const PRESETS_DATA: Preset[] = [
    // --- School Uniform ---
    {"cat": "options.presets.category.schoolUniform", "label": "options.presets.items.sailorUniform", "outfit": "Japanese sailor school uniform — navy blue sailor collar blouse, red scarf, pleated navy skirt"},
    {"cat": "options.presets.category.schoolUniform", "label": "options.presets.items.blazerUniformKR", "outfit": "Korean-style school uniform — beige blazer, white shirt, plaid skirt, ribbon tie"},
    {"cat": "options.presets.category.schoolUniform", "label": "options.presets.items.blazerUniformUK", "outfit": "British-style school uniform — dark blazer with emblem, white blouse, tie, pleated grey skirt"},
    {"cat": "options.presets.category.schoolUniform", "label": "options.presets.items.modernPEUniform", "outfit": "__random_color__modern PE uniform — fitted track jacket and pleated tennis skirt"},
    {"cat": "options.presets.category.schoolUniform", "label": "options.presets.items.schoolUniformRandom", "outfit": "__random_school_uniform__"},
    
    // --- Formal / Business ---
    {"cat": "options.presets.category.formalBusiness", "label": "options.presets.items.officeLook", "outfit": "__random_color__office look — crisp blouse, black pencil skirt"},
    {"cat": "options.presets.category.formalBusiness", "label": "options.presets.items.pinstripeSuit", "outfit": "charcoal grey pinstripe business suit — tailored blazer and matching skirt"},
    {"cat": "options.presets.category.formalBusiness", "label": "options.presets.items.semiFormalRandom", "outfit": "__random_semi_formal__"},
    {"cat": "options.presets.category.formalBusiness", "label": "options.presets.items.classicSuitRandom", "outfit": "__random_classic_suit__"},
    
    // --- Service / Uniform ---
    {"cat": "options.presets.category.service", "label": "options.presets.items.classicMaid", "outfit": "__random_color__classic French maid outfit — black dress, white apron, frilly headdress"},
    {"cat": "options.presets.category.service", "label": "options.presets.items.flightAttendant", "outfit": "__random_color__airline flight attendant uniform — tailored blazer, scarf, fitted skirt"},
    {"cat": "options.presets.category.service", "label": "options.presets.items.hotelier", "outfit": "__random_color__hotel front-desk uniform — elegant blazer, crisp blouse, name tag, pencil skirt"},
    {"cat": "options.presets.category.service", "label": "options.presets.items.departmentStoreConcierge", "outfit": "__random_color__department store concierge uniform — neat blazer, ribbon scarf, skirt"},
    {"cat": "options.presets.category.service", "label": "options.presets.items.racingModel", "outfit": "__random_color__sleek grid girl outfit — futuristic race queen uniform, cropped top, mini skirt, sponsor logos"},
    {"cat": "options.presets.category.service", "label": "options.presets.items.cheerleader", "outfit": "__random_color__cheerleader uniform — pleated mini skirt, sleeveless top with team logo, holding pom-poms"},
    {"cat": "options.presets.category.service", "label": "options.presets.items.eventHelper", "outfit": "__random_color__promotional model uniform — sleek, branded top and matching mini skirt for a trade show event"},
    {"cat": "options.presets.category.service", "label": "options.presets.items.chefRandom", "outfit": "__random_chef_uniform__"},
    {"cat": "options.presets.category.service", "label": "options.presets.items.modernMaidRandom", "outfit": "__random_modern_maid__"},
    
    // --- Medical / Public ---
    {"cat": "options.presets.category.medicalPublic", "label": "options.presets.items.nurseModern", "outfit": "modern nurse uniform — light blue scrub dress, stethoscope"},
    {"cat": "options.presets.category.medicalPublic", "label": "options.presets.items.nurseTraditional", "outfit": "traditional nurse uniform — white dress, apron, nurse cap"},
    {"cat": "options.presets.category.medicalPublic", "label": "options.presets.items.nunModern", "outfit": "modern nun habit — simplified, tailored black dress, shorter veil"},
    {"cat": "options.presets.category.medicalPublic", "label": "options.presets.items.nunTraditional", "outfit": "traditional nun habit — classic black and white habit with a long veil and wimple"},
    {"cat": "options.presets.category.medicalPublic", "label": "options.presets.items.nurseModernRandom", "outfit": "__random_nurse_modern__"},
    {"cat": "options.presets.category.medicalPublic", "label": "options.presets.items.nurseTraditionalRandom", "outfit": "__random_nurse_traditional__"},
    {"cat": "options.presets.category.medicalPublic", "label": "options.presets.items.nunModernRandom", "outfit": "__random_nun_modern__"},
    {"cat": "options.presets.category.medicalPublic", "label": "options.presets.items.nunTraditionalRandom", "outfit": "__random_nun_traditional__"},

    // --- Military & Public Security ---
    {"cat": "options.presets.category.military", "label": "options.presets.items.femaleArmy", "outfit": "__random_color__army uniform (female) — olive drab service uniform with beret"},
    {"cat": "options.presets.category.military", "label": "options.presets.items.femaleAirForce", "outfit": "__random_color__air force dress uniform (female) — deep blue tailored jacket, skirt, service cap"},
    {"cat": "options.presets.category.military", "label": "options.presets.items.femaleNavy", "outfit": "__random_color__naval dress uniform (female) — white tailored jacket and skirt with rank accents"},
    {"cat": "options.presets.category.publicSecurity", "label": "options.presets.items.femalePolice", "outfit": "__random_color__police uniform (female) — navy shirt, tactical belt, pencil skirt"},
    {"cat": "options.presets.category.publicSecurity", "label": "options.presets.items.femaleSWAT", "outfit": "__random_color__SWAT tactical uniform (female) — black tactical vest, tactical skirt, headset"},
    
    // --- Street & Subculture ---
    {"cat": "options.presets.category.streetCasual", "label": "options.presets.items.denimLook", "outfit": "denim on denim — jean jacket and a matching denim mini skirt"},
    {"cat": "options.presets.category.streetCasual", "label": "options.presets.items.streetLook", "outfit": "streetwear look — oversized hoodie, cargo mini skirt, chunky sneakers"},
    {"cat": "options.presets.category.subcultureStyle", "label": "options.presets.items.gothLook", "outfit": "gothic style — black lace dress, platform boots, dark makeup"},
    {"cat": "options.presets.category.subcultureStyle", "label": "options.presets.items.punkLook", "outfit": "punk rock style — torn band t-shirt, plaid mini skirt, combat boots, studded leather jacket"},
    {"cat": "options.presets.category.subcultureStyle", "label": "options.presets.items.sweetFrillyDress", "outfit": "__random_color__sweet frilly doll-like dress — pastel colors, frills, lace, ribbons, cute motifs like sweets and animals"},
    {"cat": "options.presets.category.subcultureStyle", "label": "options.presets.items.classicFrillyDress", "outfit": "__random_color__classic elegant doll style dress — elegant A-line silhouette, muted colors like ivory and wine red, historical motifs, less frilly"},
    {"cat": "options.presets.category.subcultureStyle", "label": "options.presets.items.gothicFrillyDress", "outfit": "__random_color__gothic doll style dress — black and dark colors like deep red or purple, lace, crosses, bats, elegant but dark aesthetic, bell-shaped skirt"},
    {"cat": "options.presets.category.subcultureStyle", "label": "options.presets.items.heroCostume", "outfit": "__random_color__ superhero costume, sleek and modern design with a cape and emblem"},
    {"cat": "options.presets.category.subcultureStyle", "label": "options.presets.items.bunnyGirl", "outfit": "__random_color__ bunny girl costume — strapless leotard, bunny ears, collar with bow tie, cuffs"},
    {"cat": "options.presets.category.streetCasual", "label": "options.presets.items.denimStreetRandom", "outfit": "__random_denim__"},
    {"cat": "options.presets.category.subcultureStyle", "label": "options.presets.items.dollStyleDressRandom", "outfit": "__random_doll_style_dress__"},
    {"cat": "options.presets.category.subcultureStyle", "label": "options.presets.items.gothicFrillyDressRandom", "outfit": "__random_gothic_doll_dress__"},

    // --- Sports & Dance ---
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.yogaOutfit", "outfit": "__random_color__yoga outfit — fitted tank top and a pleated athletic skirt"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.onePieceSwimsuit", "outfit": "__random_color__one-piece swimsuit — competitive athletic style"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.racingSwimsuit", "outfit": "__random_color__racing swimsuit — FINA-approved tech suit"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.wetsuit", "outfit": "__random_color__sleek full-body wetsuit for surfing"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.femaleCycling", "outfit": "__random_color__cycling outfit (female) — aero jersey and cycling skirt"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.femaleFigureSkating", "outfit": "__random_color__figure skating outfit (female) — sparkly skating dress with chiffon skirt"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.shortTrackSuit", "outfit": "__random_color__ short track speed skating suit — skin-tight, aerodynamic, with protective padding"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.speedSkatingSuit", "outfit": "__random_color__ speed skating suit — aerodynamic skinsuit, integrated hood"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.equestrianOutfit", "outfit": "equestrian outfit — fitted jacket, a crisp shirt, and breeches"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.balletTutu", "outfit": "__random_color__ballet tutu — classic tutu with a fitted bodice"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.balletPracticeWear", "outfit": "__random_color__ballet practice wear — leotard and wrap skirt"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.leotard", "outfit": "__random_color__sleek athletic leotard"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.kendoUniform", "outfit": "kendo uniform (kendo-gi and hakama), holding a shinai"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.judoGi", "outfit": "judo uniform (judogi) with a black belt"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.taekwondoDobok", "outfit": "taekwondo uniform (dobok) with a black belt"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.karateGi", "outfit": "karate uniform (karate-gi) with a black belt"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.tennisLookRandom", "outfit": "__random_tennis__"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.golfOutfitRandom", "outfit": "__random_golf_outfit__"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.baseballUniformRandom", "outfit": "__random_baseball_uniform__"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.soccerUniformRandom", "outfit": "__random_soccer_uniform__"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.basketballUniformRandom", "outfit": "__random_basketball_uniform__"},
    {"cat": "options.presets.category.sportsDance", "label": "options.presets.items.volleyballUniformRandom", "outfit": "__random_volleyball_uniform__"},

    // --- Stage / Club ---
    {"cat": "options.presets.category.stageClub", "label": "options.presets.items.eveningMiniDress", "outfit": "__random_color__elegant evening mini dress, cocktail party style"},
    {"cat": "options.presets.category.stageClub", "label": "options.presets.items.eveningSequinDress", "outfit": "__random_color__sparkly sequin dress, fitted silhouette, for a night club"},
    {"cat": "options.presets.category.stageClub", "label": "options.presets.items.kpopStageRandom", "outfit": "__random_kpop__"},

    // --- Season / Theme ---
    {"cat": "options.presets.category.seasonTheme", "label": "options.presets.items.winterCoat", "outfit": "stylish winter look — __random_color__ long wool coat, turtleneck sweater, plaid skirt"},
    {"cat": "options.presets.category.seasonTheme", "label": "options.presets.items.rainySeasonLook", "outfit": "rainy day fashion — __random_color__ transparent raincoat over a simple dress, holding a clear umbrella"},
    {"cat": "options.presets.category.seasonTheme", "label": "options.presets.items.autumnCheckKnit", "outfit": "autumn casual — oversized __random_color__ check-pattern knit sweater, brown corduroy mini skirt"},
    {"cat": "options.presets.category.seasonTheme", "label": "options.presets.items.weddingDress", "outfit": "elegant modern wedding dress, A-line silhouette, lace details"},

    // --- Future / Cyber ---
    {"cat": "options.presets.category.futureCyber", "label": "options.presets.items.cyberSuitNeon", "outfit": "__random_color__cybernetic suit with neon light accents, futuristic aesthetic"},
    {"cat": "options.presets.category.futureCyber", "label": "options.presets.items.techwearLook", "outfit": "techwear outfit — black functional jacket with straps, cargo skirt, tactical boots"},
    
    // --- Traditional / Folk ---
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.hanbokClassic", "outfit": "traditional hanbok — elegant white jeogori and a vibrant red chima"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.hanbokModern", "outfit": "modern hanbok — sheer pastel jeogori and a short, flowing floral chima"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.kimonoFurisode", "outfit": "traditional furisode kimono — long flowing sleeves, intricate floral and crane patterns"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.kimonoYukata", "outfit": "yukata — casual summer kimono made of cotton"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.qipaoClassic", "outfit": "classic qipao (cheongsam) — red silk brocade with phoenix embroidery, high mandarin collar, side slits"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.aoDaiClassic", "outfit": "traditional ao dai — elegant white silk, long flowing tunic over wide-leg pants"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.sariClassic", "outfit": "classic Indian sari — vibrant Kanjivaram silk with intricate gold zari border"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.dirndlClassic", "outfit": "traditional Bavarian dirndl — white blouse, fitted bodice, full skirt, and apron"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.parisianLook", "outfit": "Parisian chic look — striped Breton shirt, black mini skirt, red beret"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.cowboyLook", "outfit": "western cowboy look — denim shirt, leather vest, cowboy hat, jeans, and cowboy boots"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.hanbokModernRandom", "outfit": "__random_hanbok__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.kimonoModernRandom", "outfit": "__random_kimono__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.qipaoModernRandom", "outfit": "__random_qipao__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.aoDaiModernRandom", "outfit": "__random_ao_dai__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.sariModernRandom", "outfit": "__random_sari__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.dirndlModernRandom", "outfit": "__random_dirndl__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.hanbokTraditionalRandom", "outfit": "__random_traditional_hanbok__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.kimonoTraditionalRandom", "outfit": "__random_traditional_kimono__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.qipaoTraditionalRandom", "outfit": "__random_traditional_qipao__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.sariTraditionalRandom", "outfit": "__random_traditional_sari__"},
    {"cat": "options.presets.category.traditional", "label": "options.presets.items.dirndlTraditionalRandom", "outfit": "__random_traditional_dirndl__"},

    // --- Cosplay ---
    {"cat": "options.presets.category.cosplay", "label": "options.presets.items.cosplayStreetFighter", "outfit": "__random_cosplay_street_fighter__"},
    {"cat": "options.presets.category.cosplay", "label": "options.presets.items.cosplayTekken", "outfit": "__random_cosplay_tekken__"},
    {"cat": "options.presets.category.cosplay", "label": "options.presets.items.cosplayKOF", "outfit": "__random_cosplay_kof__"},
    {"cat": "options.presets.category.cosplay", "label": "options.presets.items.cosplaySailorMoon", "outfit": "__random_cosplay_sailor_moon__"},
    {"cat": "options.presets.category.cosplay", "label": "options.presets.items.cosplayGenshinImpact", "outfit": "__random_cosplay_genshin_impact__"},
    {"cat": "options.presets.category.cosplay", "label": "options.presets.items.ninjaOutfit", "outfit": "__random_color__ninja outfit (shinobi shozoku) — hooded mask, stealth suit, katana on back"},
    {"cat": "options.presets.category.cosplay", "label": "options.presets.items.cosplayKnightModernRandom", "outfit": "__random_knight_cosplay__"}
];

export const ASPECT_RATIOS = [
    { v: '1:1', t: 'options.aspectRatio.square' },
    { v: '3:4', t: 'options.aspectRatio.portrait' },
    { v: '4:3', t: 'options.aspectRatio.landscape' },
    { v: '9:16', t: 'options.aspectRatio.shorts' },
    { v: '16:9', t: 'options.aspectRatio.widescreen' },
    { v: '', t: 'options.aspectRatio.custom' },
];

export const CAMERA_BODIES = [
    { v: 'Sony A7R V', t: 'options.cameraBodies.sonyA7RV' },
    { v: 'Canon EOS R5', t: 'options.cameraBodies.canonEOSR5' },
    { v: 'Nikon Z9', t: 'options.cameraBodies.nikonZ9' },
    { v: 'Leica M11', t: 'options.cameraBodies.leicaM11' },
    { v: 'Fujifilm GFX 100S', t: 'options.cameraBodies.fujifilmGFX100S' },
];

export const LENSES = [
    { v: '50mm f/1.4', t: 'options.lenses.f1_4_50mm' },
    { v: '85mm f/1.2', t: 'options.lenses.f1_2_85mm' },
    { v: '35mm f/1.8', t: 'options.lenses.f1_8_35mm' },
    { v: '24-70mm f/2.8', t: 'options.lenses.f2_8_24_70mm' },
    { v: '135mm f/1.8', t: 'options.lenses.f1_8_135mm' },
    { v: '16-35mm f/2.8', t: 'options.lenses.f2_8_16_35mm' },
];

export const WB_OPTIONS = [
    { v: '', t: 'options.wb.auto' },
    { v: '5500K', t: 'options.wb.daylight' },
    { v: '6500K', t: 'options.wb.cloudy' },
    { v: '3200K', t: 'options.wb.tungsten' },
    { v: '4000K', t: 'options.wb.fluorescent' },
];

export const CAMERA_COMPOSITION_OPTIONS = [
    { v: '', t: 'options.composition.default' },
    { v: 'rules of thirds', t: 'options.composition.rulesOfThirds' },
    { v: 'leading lines', t: 'options.composition.leadingLines' },
    { v: 'symmetry', t: 'options.composition.symmetry' },
    { v: 'composition following the golden ratio', t: 'options.composition.goldenRatio' },
    { v: 'framing', t: 'options.composition.framing' },
    { v: 'depth of field', t: 'options.composition.depthOfField' },
    { v: 'close-up shot', t: 'options.composition.closeUp' },
    { v: 'extreme close-up shot', t: 'options.composition.extremeCloseUp' },
    { v: 'medium shot', t: 'options.composition.mediumShot' },
    { v: 'cowboy shot', t: 'options.composition.cowboyShot' },
    { v: 'full shot', t: 'options.composition.fullShot' },
    { v: 'long shot', t: 'options.composition.longShot' },
    { v: 'low angle shot', t: 'options.composition.lowAngle' },
    { v: 'high angle shot', t: 'options.composition.highAngle' },
    { v: 'dutch angle', t: 'options.composition.dutchAngle' },
    { v: "bird's eye view", t: 'options.composition.birdsEyeView' },
    { v: "worm's eye view", t: 'options.composition.wormsEyeView' },
];

export const TIME_OF_DAY_OPTIONS = [
    { v: '', t: 'options.timeOfDay.auto' },
    { v: '__random__', t: 'options.timeOfDay.random' },
    { v: 'golden hour', t: 'options.timeOfDay.goldenHour' },
    { v: 'blue hour', t: 'options.timeOfDay.blueHour' },
    { v: 'midday sun', t: 'options.timeOfDay.middaySun' },
    { v: 'night', t: 'options.timeOfDay.night' },
    { v: 'dawn', t: 'options.timeOfDay.dawn' },
    { v: 'dusk', t: 'options.timeOfDay.dusk' },
    { v: 'high noon', t: 'options.timeOfDay.highNoon' },
    { v: 'twilight', t: 'options.timeOfDay.twilight' },
    { v: 'midnight', t: 'options.timeOfDay.midnight' },
    { v: 'overcast daylight', t: 'options.timeOfDay.overcastDaylight' },
];

export const WEATHER_OPTIONS = [
    { v: '', t: 'options.weather.auto' },
    { v: '__random__', t: 'options.weather.random' },
    { v: 'clear skies', t: 'options.weather.clear' },
    { v: 'partly cloudy', t: 'options.weather.partlyCloudy' },
    { v: 'overcast', t: 'options.weather.overcast' },
    { v: 'light rain', t: 'options.weather.lightRain' },
    { v: 'heavy rain', t: 'options.weather.heavyRain' },
    { v: 'snowing', t: 'options.weather.snowing' },
    { v: 'foggy', t: 'options.weather.foggy' },
    { v: 'thunderstorm', t: 'options.weather.thunderstorm' },
    { v: 'blizzard', t: 'options.weather.blizzard' },
    { v: 'sandstorm', t: 'options.weather.sandstorm' },
    { v: 'misty', t: 'options.weather.misty' },
    { v: 'aurora borealis', t: 'options.weather.aurora' },
    { v: 'hazy sunshine', t: 'options.weather.hazy' },
    { v: 'rainbow after rain', t: 'options.weather.rainbow' },
];

export const ATMOSPHERE_OPTIONS = [
    { v: '', t: 'options.atmosphere.none' },
    { v: 'Horror', t: 'options.atmosphere.horror' },
    { v: 'Sci-Fi', t: 'options.atmosphere.sciFi' },
    { v: 'Fantasy', t: 'options.atmosphere.fantasy' },
    { v: 'Blockbuster Movie', t: 'options.atmosphere.blockbuster' },
    { v: 'Medieval', t: 'options.atmosphere.medieval' },
    { v: 'Korean Classic', t: 'options.atmosphere.koreanClassic' },
    { v: 'Japanese Classic', t: 'options.atmosphere.japaneseClassic' },
    { v: 'Chinese Classic', t: 'options.atmosphere.chineseClassic' },
    { v: 'Oriental Classic', t: 'options.atmosphere.orientalClassic' },
];

export const BACKGROUND_OPTIONS = [
    { v: '', t: 'options.background.auto' },
    { v: '__random__', t: 'options.background.random' },
    { v: 'cafe interior', t: 'options.background.cafe' },
    { v: 'city street at night', t: 'options.background.cityNight' },
    { v: 'modern library', t: 'options.background.library' },
    { v: 'beach at sunset', t: 'options.background.beach' },
    { v: 'lush forest', t: 'options.background.forest' },
    { v: 'rooftop with city view', t: 'options.background.rooftop' },
    { v: 'traditional Korean palace', t: 'options.background.koreanPalace' },
    { v: 'futuristic neon-lit alley', t: 'options.background.cyberpunkAlley' },
    { v: 'cozy bedroom', t: 'options.background.bedroom' },
    { v: 'grand ballroom', t: 'options.background.grandBallroom' },
    { v: 'science laboratory', t: 'options.background.scienceLab' },
    { v: 'artist studio', t: 'options.background.artistStudio' },
    { v: 'rooftop bar at night', t: 'options.background.rooftopBar' },
    { v: 'bustling marketplace', t: 'options.background.marketplace' },
    { v: 'serene mountain peak', t: 'options.background.mountainPeak' },
    { v: 'dense jungle with waterfall', t: 'options.background.jungleWaterfall' },
    { v: 'underwater coral reef', t: 'options.background.underwaterReef' },
    { v: 'snowy arctic landscape', t: 'options.background.arctic' },
    { v: 'ancient ruins', t: 'options.background.ancientRuins' },
    { v: 'medieval castle interior', t: 'options.background.castleInterior' },
    { v: 'steampunk city street', t: 'options.background.steampunkCity' },
    { v: 'spaceship bridge', t: 'options.background.spaceshipBridge' },
    { v: 'surreal dreamscape', t: 'options.background.dreamscape' },
    { v: 'abandoned industrial warehouse', t: 'options.background.warehouse' },
    { v: 'subway platform', t: 'options.background.subway' },
];

export const AGE_OPTIONS = [
    { v: '', t: 'options.age.default' },
    { v: '__random__', t: 'options.age.random' },
    { v: 'teenager', t: 'options.age.teenager' },
    { v: 'woman in her early 20s', t: 'options.age.early20s' },
    { v: 'woman in her mid 20s', t: 'options.age.mid20s' },
    { v: 'woman in her late 20s', t: 'options.age.late20s' },
    { v: 'woman in her 30s', t: 'options.age.in30s' },
    { v: 'woman in her 40s', t: 'options.age.in40s' },
];

export const CHARACTER_OPTIONS = [
    { v: '', t: 'options.character.default' },
    { v: '__random__', t: 'options.character.random' },
    { v: 'east asian', t: 'options.character.eastAsian' },
    { v: 'caucasian', t: 'options.character.caucasian' },
    { v: 'black', t: 'options.character.black' },
    { v: 'korean', t: 'options.character.korean' },
    { v: 'japanese', t: 'options.character.japanese' },
    { v: 'chinese', t: 'options.character.chinese' },
    { v: 'taiwanese', t: 'options.character.taiwanese' },
    { v: 'thai', t: 'options.character.thai' },
    { v: 'vietnamese', t: 'options.character.vietnamese' },
    { v: 'filipina', t: 'options.character.filipina' },
    { v: 'indonesian', t: 'options.character.indonesian' },
    { v: 'malaysian', t: 'options.character.malaysian' },
    { v: 'mongolian', t: 'options.character.mongolian' },
    { v: 'indian', t: 'options.character.indian' },
    { v: 'middle eastern', t: 'options.character.middleEastern' },
    { v: 'american', t: 'options.character.american' },
    { v: 'british', t: 'options.character.british' },
    { v: 'french', t: 'options.character.french' },
    { v: 'german', t: 'options.character.german' },
    { v: 'russian', t: 'options.character.russian' },
    { v: 'scandinavian', t: 'options.character.scandinavian' },
    { v: 'hispanic', t: 'options.character.hispanic' },
    { v: 'brazilian', t: 'options.character.brazilian' },
];

export const NUMBER_OF_PEOPLE_OPTIONS = [
    { v: '1', t: 'options.numberOfPeople.one' },
    { v: '2', t: 'options.numberOfPeople.two' },
    { v: '3', t: 'options.numberOfPeople.three' },
    { v: '4', t: 'options.numberOfPeople.four' },
    { v: '5', t: 'options.numberOfPeople.five' },
    { v: '__random__', t: 'options.numberOfPeople.random' },
];

export const HAIR_STYLE_OPTIONS = Object.entries({
    default: "Default", random: "Random", pixieCut: "Pixie Cut", shortBob: "Short Bob", bowlCut: "Bowl Cut", shortWolfCut: "Short Wolf Cut", slickedBack: "Slicked Back Short Hair", bobCut: "Bob Cut", cCurlBob: "C-Curl Bob", aLineBob: "A-Line Bob", layeredBob: "Layered Bob", pageboyCut: "Pageboy Cut", mediumLength: "Medium Length Hair", himeCut: "Hime Cut", wolfCut: "Wolf Cut", shagCut: "Shag Cut", jellyfishCut: "Jellyfish Cut", longStraight: "Long Straight Hair", longWavy: "Long Wavy Hair", longCurly: "Long Curly Hair", waistLength: "Waist-Length Hair", floorLength: "Floor-Length Hair", elizabethPerm: "Elizabeth Perm", goddessPerm: "Goddess Perm", jellyPerm: "Jelly Perm", layeredLong: "Layered Long Hair", seeThroughBangs: "See-Through Bangs", choppyBangs: "Choppy Bangs", bluntBangs: "Blunt Bangs", curtainBangs: "Curtain Bangs", fullBangs: "Full Bangs", wideBangs: "Wide Bangs", softBangs: "Soft Bangs", sideBangs: "Side Bangs", ponytail: "Ponytail", highPonytail: "High Ponytail", lowPonytail: "Low Ponytail", sidePonytail: "Side Ponytail", twinTails: "Twin Tails", braidedPigtails: "Braided Pigtails", halfUp: "Half-Up Hair", bun: "Bun", messyBun: "Messy Bun", spaceBuns: "Space Buns", odango: "Odango", braid: "Braid", dutchBraids: "Dutch Braids", frenchBraid: "French Braid", dreadlocks: "Dreadlocks", longDreadlocks: "Floor-Length Dreadlocks", afro: "Afro", largeAfro: "Large Afro", cornrows: "Cornrows", mohawk: "Mohawk", fingerWaveBob1920s: "1920s Finger Wave Bob", beehive1960s: "1960s Beehive", punkPerm1980s: "1980s Punk Perm", victorianUpdo: "Victorian Updo", medievalNoble: "Medieval Noble Hairstyle", koreanGache: "Korean Gache", japaneseShimada: "Japanese Shimada", chineseTang: "Chinese Tang Dynasty", chineseWuxia: "Chinese Wuxia Heroine", egyptianBraided: "Ancient Egyptian Braided"
}).map(([key, _]) => ({ v: key === 'default' ? '' : (key === 'random' ? '__random__' : key.replace(/([A-Z])/g, ' $1').toLowerCase()), t: `options.hairStyle.${key}` }));


export const LENGTH_INCOMPATIBLE_HAIRSTYLES = new Set(['pixie cut', 'short bob', 'bowl cut', 'short wolf cut', 'slicked back short hair', 'pageboy cut', 'mohawk', '1920s finger wave bob']);

export const HAIR_LENGTH_OPTIONS = [
    { v: '', t: 'options.hairLength.default' },
    { v: 'shoulder-length', t: 'options.hairLength.shoulder' },
    { v: 'waist-length', t: 'options.hairLength.waist' },
    { v: 'knee-length', t: 'options.hairLength.knee' },
    { v: 'ankle-length', t: 'options.hairLength.ankle' },
];

export const HAIR_COLOR_OPTIONS = [
    { v: '', t: 'options.hairColor.default' },
    { v: '__random__', t: 'options.hairColor.random' },
    { v: 'black', t: 'options.hairColor.black' },
    { v: 'jet black', t: 'options.hairColor.jetBlack' },
    { v: 'dark brown', t: 'options.hairColor.darkBrown' },
    { v: 'chocolate brown', t: 'options.hairColor.chocolateBrown' },
    { v: 'light brown', t: 'options.hairColor.lightBrown' },
    { v: 'ash brown', t: 'options.hairColor.ashBrown' },
    { v: 'blonde', t: 'options.hairColor.blonde' },
    { v: 'ash blonde', t: 'options.hairColor.ashBlonde' },
    { v: 'platinum blonde', t: 'options.hairColor.platinumBlonde' },
    { v: 'silver', t: 'options.hairColor.silver' },
    { v: 'white', t: 'options.hairColor.white' },
    { v: 'ash grey', t: 'options.hairColor.ashGrey' },
    { v: 'red', t: 'options.hairColor.red' },
    { v: 'burgundy', t: 'options.hairColor.burgundy' },
    { v: 'orange', t: 'options.hairColor.orange' },
    { v: 'pink', t: 'options.hairColor.pink' },
    { v: 'blue', t: 'options.hairColor.blue' },
    { v: 'dodger blue', t: 'options.hairColor.dodgerBlue' },
    { v: 'sky blue', t: 'options.hairColor.skyBlue' },
    { v: 'green', t: 'options.hairColor.green' },
    { v: 'mint green', t: 'options.hairColor.mintGreen' },
    { v: 'purple', t: 'options.hairColor.purple' },
    { v: 'lavender', t: 'options.hairColor.lavender' },
    { v: 'gold', t: 'options.hairColor.gold' },
    { v: 'light pink', t: 'options.hairColor.lightPink' },
    { v: 'hot pink', t: 'options.hairColor.hotPink' },
    { v: 'deep pink', t: 'options.hairColor.deepPink' },
    { v: 'pale violet red', t: 'options.hairColor.paleVioletRed' },
    { v: 'medium violet red', t: 'options.hairColor.mediumVioletRed' },
    { v: 'light salmon', t: 'options.hairColor.lightSalmon' },
    { v: 'salmon', t: 'options.hairColor.salmon' },
    { v: 'dark salmon', t: 'options.hairColor.darkSalmon' },
    { v: 'light coral', t: 'options.hairColor.lightCoral' },
    { v: 'indian red', t: 'options.hairColor.indianRed' },
    { v: 'crimson', t: 'options.hairColor.crimson' },
    { v: 'firebrick', t: 'options.hairColor.firebrick' },
    { v: 'dark red', t: 'options.hairColor.darkRed' },
    { v: 'orange red', t: 'options.hairColor.orangeRed' },
    { v: 'tomato', t: 'options.hairColor.tomato' },
    { v: 'coral', t: 'options.hairColor.coral' },
    { v: 'dark orange', t: 'options.hairColor.darkOrange' },
    { v: 'yellow', t: 'options.hairColor.yellow' },
    { v: 'light yellow', t: 'options.hairColor.lightYellow' },
    { v: 'lemon chiffon', t: 'options.hairColor.lemonChiffon' },
    { v: 'light goldenrod yellow', t: 'options.hairColor.lightGoldenrodYellow' },
    { v: 'papaya whip', t: 'options.hairColor.papayaWhip' },
    { v: 'moccasin', t: 'options.hairColor.moccasin' },
    { v: 'peach puff', t: 'options.hairColor.peachPuff' },
    { v: 'pale goldenrod', t: 'options.hairColor.paleGoldenrod' },
    { v: 'khaki', t: 'options.hairColor.khaki' },
    { v: 'dark khaki', t: 'options.hairColor.darkKhaki' },
    { v: 'cornsilk', t: 'options.hairColor.cornsilk' },
    { v: 'blanched almond', t: 'options.hairColor.blanchedAlmond' },
    { v: 'bisque', t: 'options.hairColor.bisque' },
    { v: 'navajo white', t: 'options.hairColor.navajoWhite' },
    { v: 'wheat', t: 'options.hairColor.wheat' },
    { v: 'burlywood', t: 'options.hairColor.burlywood' },
    { v: 'tan', t: 'options.hairColor.tan' },
    { v: 'rosy brown', t: 'options.hairColor.rosyBrown' },
    { v: 'sandy brown', t: 'options.hairColor.sandyBrown' },
    { v: 'goldenrod', t: 'options.hairColor.goldenrod' },
    { v: 'dark goldenrod', t: 'options.hairColor.darkGoldenrod' },
    { v: 'peru', t: 'options.hairColor.peru' },
    { v: 'chocolate', t: 'options.hairColor.chocolate' },
    { v: 'saddle brown', t: 'options.hairColor.saddleBrown' },
    { v: 'sienna', t: 'options.hairColor.sienna' },
    { v: 'brown', t: 'options.hairColor.brown' },
    { v: 'maroon', t: 'options.hairColor.maroon' },
    { v: 'dark olive green', t: 'options.hairColor.darkOliveGreen' },
    { v: 'olive', t: 'options.hairColor.olive' },
    { v: 'olive drab', t: 'options.hairColor.oliveDrab' },
    { v: 'yellow green', t: 'options.hairColor.yellowGreen' },
    { v: 'lime green', t: 'options.hairColor.limeGreen' },
    { v: 'lime', t: 'options.hairColor.lime' },
    { v: 'lawn green', t: 'options.hairColor.lawnGreen' },
    { v: 'chartreuse', t: 'options.hairColor.chartreuse' },
    { v: 'green yellow', t: 'options.hairColor.greenYellow' },
    { v: 'spring green', t: 'options.hairColor.springGreen' },
    { v: 'medium spring green', t: 'options.hairColor.mediumSpringGreen' },
    { v: 'light green', t: 'options.hairColor.lightGreen' },
    { v: 'pale green', t: 'options.hairColor.paleGreen' },
    { v: 'dark sea green', t: 'options.hairColor.darkSeaGreen' },
    { v: 'medium sea green', t: 'options.hairColor.mediumSeaGreen' },
    { v: 'sea green', t: 'options.hairColor.seaGreen' },
    { v: 'forest green', t: 'options.hairColor.forestGreen' },
    { v: 'dark green', t: 'options.hairColor.darkGreen' },
    { v: 'medium aquamarine', t: 'options.hairColor.mediumAquamarine' },
    { v: 'aqua', t: 'options.hairColor.aqua' },
    { v: 'cyan', t: 'options.hairColor.cyan' },
    { v: 'light cyan', t: 'options.hairColor.lightCyan' },
    { v: 'pale turquoise', t: 'options.hairColor.paleTurquoise' },
    { v: 'aquamarine', t: 'options.hairColor.aquamarine' },
    { v: 'turquoise', t: 'options.hairColor.turquoise' },
    { v: 'medium turquoise', t: 'options.hairColor.mediumTurquoise' },
    { v: 'dark turquoise', t: 'options.hairColor.darkTurquoise' },
    { v: 'light sea green', t: 'options.hairColor.lightSeaGreen' },
    { v: 'cadet blue', t: 'options.hairColor.cadetBlue' },
    { v: 'dark cyan', t: 'options.hairColor.darkCyan' },
    { v: 'teal', t: 'options.hairColor.teal' },
    { v: 'light steel blue', t: 'options.hairColor.lightSteelBlue' },
    { v: 'powder blue', t: 'options.hairColor.powderBlue' },
    { v: 'light blue', t: 'options.hairColor.lightBlue' },
    { v: 'light sky blue', t: 'options.hairColor.lightSkyBlue' },
    { v: 'deep sky blue', t: 'options.hairColor.deepSkyBlue' },
    { v: 'cornflower blue', t: 'options.hairColor.cornflowerBlue' },
    { v: 'steel blue', t: 'options.hairColor.steelBlue' },
    { v: 'royal blue', t: 'options.hairColor.royalBlue' },
    { v: 'medium blue', t: 'options.hairColor.mediumBlue' },
    { v: 'dark blue', t: 'options.hairColor.darkBlue' },
    { v: 'navy', t: 'options.hairColor.navy' },
    { v: 'midnight blue', t: 'options.hairColor.midnightBlue' },
    { v: 'thistle', t: 'options.hairColor.thistle' },
    { v: 'plum', t: 'options.hairColor.plum' },
    { v: 'fuchsia', t: 'options.hairColor.fuchsia' },
    { v: 'two-tone (black/pink)', t: 'options.hairColor.twoToneBlackPink' },
    { v: 'rainbow', t: 'options.hairColor.rainbow' },
];

export const HAT_OPTIONS = [
    { v: '', t: 'options.hat.none' },
    { v: 'baseball cap', t: 'options.hat.baseballCap' },
    { v: 'beanie', t: 'options.hat.beanie' },
    { v: 'beret', t: 'options.hat.beret' },
    { v: 'bucket hat', t: 'options.hat.bucketHat' },
    { v: 'fedora', t: 'options.hat.fedora' },
    { v: 'sun hat', t: 'options.hat.sunHat' },
    { v: 'newsboy cap', t: 'options.hat.newsboyCap' },
    { v: 'cowboy hat', t: 'options.hat.cowboyHat' },
    { v: 'top hat', t: 'options.hat.topHat' },
    { v: 'sailor hat', t: 'options.hat.sailorHat' },
    { v: 'witch hat', t: 'options.hat.witchHat' },
    { v: 'headband', t: 'options.hat.headband' },
    { v: 'large ribbon', t: 'options.hat.largeRibbon' },
    { v: 'flower crown', t: 'options.hat.flowerCrown' },
    { v: 'tiara', t: 'options.hat.tiara' },
    { v: 'nurse cap', t: 'options.hat.nurseCap' },
    { v: 'police cap', t: 'options.hat.policeCap' },
    { v: 'pilot cap', t: 'options.hat.pilotCap' },
    { v: 'Korean gat', t: 'options.hat.koreanGat' },
];

export const GLASSES_OPTIONS = [
    { v: '', t: 'options.glasses.none' },
    { v: 'eyeglasses', t: 'options.glasses.eyeglasses' },
    { v: 'sunglasses', t: 'options.glasses.sunglasses' },
    { v: 'horn-rimmed glasses', t: 'options.glasses.hornRimmed' },
    { v: 'rimless glasses', t: 'options.glasses.rimless' },
    { v: 'cat-eye glasses', t: 'options.glasses.catEye' },
    { v: 'aviator sunglasses', t: 'options.glasses.aviator' },
    { v: 'round glasses', t: 'options.glasses.round' },
    { v: 'monocle', t: 'options.glasses.monocle' },
    { v: 'goggles', t: 'options.glasses.goggles' },
    { v: 'cyberpunk visor', t: 'options.glasses.cyberpunkVisor' },
];

export const EARRING_OPTIONS = [
    { v: '', t: 'options.earrings.none' },
    { v: 'hoop earrings', t: 'options.earrings.hoop' },
    { v: 'stud earrings', t: 'options.earrings.stud' },
    { v: 'dangle earrings', t: 'options.earrings.dangle' },
    { v: 'ear cuffs', t: 'options.earrings.earCuffs' },
    { v: 'pearl earrings', t: 'options.earrings.pearl' },
    { v: 'chandelier earrings', t: 'options.earrings.chandelier' },
    { v: 'cross earrings', t: 'options.earrings.cross' },
];

export const NECKLACE_OPTIONS = [
    { v: '', t: 'options.necklace.none' },
    { v: 'choker', t: 'options.necklace.choker' },
    { v: 'pendant necklace', t: 'options.necklace.pendant' },
    { v: 'chain necklace', t: 'options.necklace.chain' },
    { v: 'pearl necklace', t: 'options.necklace.pearl' },
    { v: 'locket necklace', t: 'options.necklace.locket' },
    { v: 'rosary', t: 'options.necklace.rosary' },
    { v: 'dog tag', t: 'options.necklace.dogTag' },
    { v: 'layered necklace', t: 'options.necklace.layered' },
];

export const BAG_OPTIONS = [
    { v: '', t: 'options.bag.none' },
    { v: 'tote bag', t: 'options.bag.tote' },
    { v: 'crossbody bag', t: 'options.bag.crossbody' },
    { v: 'backpack', t: 'options.bag.backpack' },
    { v: 'clutch', t: 'options.bag.clutch' },
    { v: 'shoulder bag', t: 'options.bag.shoulder' },
    { v: 'briefcase', t: 'options.bag.briefcase' },
    { v: 'hobo bag', t: 'options.bag.hobo' },
    { v: 'messenger bag', t: 'options.bag.messenger' },
    { v: 'fanny pack', t: 'options.bag.fannyPack' },
    { v: 'doctor bag', t: 'options.bag.doctor' },
    { v: 'eco bag', t: 'options.bag.eco' },
];

export const WEAPON_OPTIONS = [
    { v: '', t: 'options.weapon.none' },
    { v: '__random__', t: 'options.weapon.random' },
    { v: 'assault rifle', t: 'options.weapon.assaultRifle' },
    { v: 'revolver', t: 'options.weapon.revolver' },
    { v: 'automatic pistol', t: 'options.weapon.automaticPistol' },
    { v: 'sniper rifle', t: 'options.weapon.sniperRifle' },
    { v: 'katana', t: 'options.weapon.katana' },
    { v: 'lightsaber', t: 'options.weapon.lightsaber' },
    { v: 'greatsword', t: 'options.weapon.greatsword' },
    { v: 'greataxe', t: 'options.weapon.greataxe' },
    { v: 'dual katanas', t: 'options.weapon.dualKatanas' },
    { v: 'glaive (woldo)', t: 'options.weapon.glaive' },
    { v: 'very long katana', t: 'options.weapon.veryLongKatana' },
    { v: 'huge greatsword', t: 'options.weapon.hugeGreatsword' },
    { v: 'huge greataxe', t: 'options.weapon.hugeGreataxe' },
    { v: 'huge mace', t: 'options.weapon.hugeMace' },
    { v: 'colossal odachi', t: 'options.weapon.colossalOdachi' },
    { v: 'monstrous greatsword', t: 'options.weapon.monstrousGreatsword' },
    { v: 'titanic greataxe', t: 'options.weapon.titanicGreataxe' },
    { v: 'gigantic mace', t: 'options.weapon.giganticMace' },
    { v: 'colossal spear', t: 'options.weapon.colossalSpear' },
    { v: 'colossal halberd', t: 'options.weapon.colossalHalberd' },
    { v: 'surf fishing rod', t: 'options.weapon.surfFishingRod' },
];

export const WEAPON_QUANTITY_OPTIONS = [
    { v: '1', t: 'options.weaponQuantity.one' },
    { v: '2', t: 'options.weaponQuantity.two' },
    { v: 'multiple', t: 'options.weaponQuantity.multiple' },
];

export const PLURAL_WEAPONS = new Set(['dual katanas', 'surf fishing rod']);

export const ASSAULT_RIFLE_MODELS = ['AK-47 assault rifle', 'M4A1 carbine', 'FN SCAR-L assault rifle', 'Heckler & Koch HK416 assault rifle', 'Steyr AUG A3 assault rifle'];
export const REVOLVER_MODELS = ['Colt Python revolver', 'Smith & Wesson Model 686 revolver', 'Ruger GP100 revolver', 'Chiappa Rhino revolver'];
export const PISTOL_MODELS = ['Glock 19 pistol', 'Beretta 92FS pistol', 'SIG Sauer P226 pistol', 'Colt M1911 pistol', 'IMI Desert Eagle pistol'];
export const SNIPER_RIFLE_MODELS = ['Barrett M82A1 sniper rifle', 'Accuracy International AWM sniper rifle', 'CheyTac M200 Intervention sniper rifle', 'McMillan TAC-50C sniper rifle', 'AS50 sniper rifle'];

export const ERA_OPTIONS = [
    { v: '', t: 'options.era.default' },
    { v: '1980s film grain', t: 'options.era.y1980s' },
    { v: '1990s film grain', t: 'options.era.y1990s' },
    { v: '2000s digital photo', t: 'options.era.y2000s' },
    { v: '2010s digital photo', t: 'options.era.y2010s' },
    { v: 'vintage film photo', t: 'options.era.vintageFilm' },
    { v: 'cyberpunk film aesthetic', t: 'options.era.cyberpunkFilm' },
];

export const FIXED_PROMPTS = [
    { key: 'quality', label: 'options.fixedPrompts.quality', prompt: 'masterpiece, best quality' },
    { key: 'details', label: 'options.fixedPrompts.details', prompt: 'ultra-detailed, intricate details' },
    { key: 'photo', label: 'options.fixedPrompts.photo', prompt: 'photorealistic, 8k' },
    { key: 'full_body', label: 'options.fixedPrompts.fullBody', prompt: 'full body shot' },
    { key: 'outstanding_beauty', label: 'options.fixedPrompts.outstandingBeauty', prompt: 'extremely beautiful, very outstanding beauty' },
    { key: 'sd_style', label: 'options.fixedPrompts.sd_style', prompt: 'photorealistic photograph of a cute chibi figure, super deformed (SD) style, 2 heads tall, large expressive eyes, realistic skin texture, detailed face, cinematic lighting, 8k, DSLR' },
    { key: 'hourglass_waist', label: 'options.fixedPrompts.hourglassWaist', prompt: '' },
    { key: 'ripped', label: 'options.fixedPrompts.ripped', prompt: '' },
];

export const LEGWEAR_OPTIONS: LegwearOption[] = [
    { v: '', t: 'options.legwear.none' },
    { v: 'random-pantyhose', t: 'options.legwear.randomAny' },
    { v: 'random-pattern', t: 'options.legwear.randomPattern' },
    { v: 'random-season', t: 'options.legwear.randomSeasonal' },
    { v: 'random-color', t: 'options.legwear.randomVividColor' },
    { v: 'random-finish', t: 'options.legwear.randomFinish' },
    { v: 'random-animation', t: 'options.legwear.randomAnimation' },
    { v: 'random-lettering', t: 'options.legwear.randomLettering' },
    { v: 'random-tattoo', t: 'options.legwear.randomTattoo' },
    { v: 'random-cartoon', t: 'options.legwear.randomCartoon' },
    { v: 'random-latex', t: 'options.legwear.randomLatex' },
];

export const STOCKINGS_OPTIONS: LegwearOption[] = [
    { v: '', t: 'options.stockings.none' },
    { v: 'random-stockings', t: 'options.stockings.randomAny' },
    { v: 'random-stockings-pattern', t: 'options.stockings.randomPattern' },
    { v: 'random-stockings-season', t: 'options.stockings.randomSeasonal' },
    { v: 'random-stockings-color', t: 'options.stockings.randomVividColor' },
    { v: 'random-stockings-finish', t: 'options.stockings.randomFinish' },
    { v: 'random-stockings-animation', t: 'options.stockings.randomAnimation' },
    { v: 'random-stockings-lettering', t: 'options.stockings.randomLettering' },
    { v: 'random-stockings-tattoo', t: 'options.stockings.randomTattoo' },
    { v: 'random-stockings-cartoon', t: 'options.stockings.randomCartoon' },
    { v: 'random-stockings-latex', t: 'options.stockings.randomLatex' },
];

export const STOCKING_LENGTH_OPTIONS = [
    { v: 'thigh-high stockings', t: 'options.stockingLength.thighHigh' },
    { v: 'knee-high stockings', t: 'options.stockingLength.kneeHigh' },
    { v: 'calf-high stockings', t: 'options.stockingLength.calfHigh' },
    { v: 'ankle-high stockings', t: 'options.stockingLength.ankleHigh' },
];

export const LEGGINGS_OPTIONS: LegwearOption[] = [
    { v: '', t: 'options.leggings.none' },
    { v: 'random-leggings', t: 'options.leggings.randomAny' },
    { v: 'random-leggings-pattern', t: 'options.leggings.randomPattern' },
    { v: 'random-leggings-season', t: 'options.leggings.randomSeasonal' },
    { v: 'random-leggings-color', t: 'options.leggings.randomVividColor' },
    { v: 'random-leggings-finish', t: 'options.leggings.randomFinish' },
    { v: 'random-leggings-animation', t: 'options.leggings.randomAnimation' },
    { v: 'random-leggings-lettering', t: 'options.leggings.randomLettering' },
    { v: 'random-leggings-tattoo', t: 'options.leggings.randomTattoo' },
    { v: 'random-leggings-cartoon', t: 'options.leggings.randomCartoon' },
    { v: 'black cotton leggings', t: 'options.leggings.blackCotton' },
    { v: 'grey cotton leggings', t: 'options.leggings.greyCotton' },
    { v: 'black faux-leather leggings', t: 'options.leggings.blackFauxLeather' },
    { v: 'black wet-look leggings', t: 'options.leggings.blackWetLook' },
    { v: 'leopard print leggings', t: 'options.leggings.leopardPrint' },
    { v: 'camouflage leggings', t: 'options.leggings.camouflage' },
];

export const SOCKS_OPTIONS: LegwearOption[] = [
    { v: '', t: 'options.socks.none' },
    { v: 'random-socks', t: 'options.socks.randomAny' },
    { v: 'random-socks-pattern', t: 'options.socks.randomPattern' },
    { v: 'random-socks-season', t: 'options.socks.randomSeasonal' },
    { v: 'random-socks-color', t: 'options.socks.randomVividColor' },
    { v: 'random-socks-finish', t: 'options.socks.randomFinish' },
    { v: 'random-socks-animation', t: 'options.socks.randomAnimation' },
    { v: 'random-socks-lettering', t: 'options.socks.randomLettering' },
    { v: 'random-socks-tattoo', t: 'options.socks.randomTattoo' },
    { v: 'random-socks-cartoon', t: 'options.socks.randomCartoon' },
    { v: 'random-socks-latex', t: 'options.socks.randomLatex' },
];

export const SOCK_LENGTH_OPTIONS = [
    { v: 'thigh-high socks', t: 'options.sockLength.thighHigh' },
    { v: 'over-the-knee socks', t: 'options.sockLength.overTheKnee' },
    { v: 'knee-high socks', t: 'options.sockLength.kneeHigh' },
    { v: 'crew socks', t: 'options.sockLength.crew' },
    { v: 'ankle socks', t: 'options.sockLength.ankle' },
];

export const SHOE_QUICK_OPTIONS = [
    { v: 'auto', t: 'options.shoeQuick.auto' },
    { v: 'random', t: 'options.shoeQuick.random' },
    { v: 'barefoot', t: 'options.shoeQuick.barefoot' },
    { v: 'low-heel pumps', t: 'options.shoeQuick.lowHeelPumps' },
    { v: 'white sneakers', t: 'options.shoeQuick.whiteSneakers' },
    { v: 'black loafers', t: 'options.shoeQuick.blackLoafers' },
    { v: 'ankle boots', t: 'options.shoeQuick.ankleBoots' },
    { v: 'combat boots', t: 'options.shoeQuick.combatBoots' },
];

export const SHOES: { v: string, t: string }[] = [
    { v: 'Low-heel Black Pumps (6cm)', t: 'options.shoes.lowHeelPumps' },
    { v: 'Stiletto Pumps (8cm)', t: 'options.shoes.stilettoPumps' },
    { v: 'Mary Jane Heels (5–7cm)', t: 'options.shoes.maryJaneHeels' },
    { v: 'Strappy Heels', t: 'options.shoes.strappyHeels' },
    { v: 'White Leather Sneakers', t: 'options.shoes.whiteSneakers' },
    { v: 'Platform Sneakers', t: 'options.shoes.platformSneakers' },
    { v: 'Retro Runner Sneakers', t: 'options.shoes.retroSneakers' },
    { v: 'Court Sneakers', t: 'options.shoes.courtSneakers' },
    { v: 'Chunky Sneakers', t: 'options.shoes.chunkySneakers' },
    { v: 'Black Patent Loafers', t: 'options.shoes.blackLoafers' },
    { v: 'Oxford Shoes', t: 'options.shoes.oxfordShoes' },
    { v: 'Ballet Flats', t: 'options.shoes.balletFlats' },
    { v: 'Ankle Boots', t: 'options.shoes.ankleBoots' },
    { v: 'Chelsea Boots', t: 'options.shoes.chelseaBoots' },
    { v: 'Combat Boots', t: 'options.shoes.combatBoots' },
    { v: 'Knee-high Boots', t: 'options.shoes.kneeHighBoots' },
    { v: 'Over-the-knee Boots', t: 'options.shoes.overTheKneeBoots' },
    { v: 'Western Boots', t: 'options.shoes.westernBoots' },
    { v: 'Figure Skates', t: 'options.shoes.figureSkates' },
    { v: 'Modern Danghye-inspired Heels', t: 'options.shoes.modernDanghye' },
    { v: 'Korean Traditional Danghye', t: 'options.shoes.koreanDanghye' },
    { v: 'Korean Traditional Gatsin', t: 'options.shoes.koreanGatsin' },
    { v: 'Japanese Geta', t: 'options.shoes.japaneseGeta' },
    { v: 'Japanese Zori', t: 'options.shoes.japaneseZori' },
    { v: 'Barefoot', t: 'options.shoes.barefoot' },
];

export const VEHICLE_OPTIONS = [
    { v: '', t: 'options.vehicles.none' },
    { v: '__random__', t: 'options.vehicles.random' },
    // Land
    { v: 'bicycle', t: 'options.vehicles.bicycle' },
    { v: 'motorcycle', t: 'options.vehicles.motorcycle' },
    { v: 'sedan', t: 'options.vehicles.sedan' },
    { v: 'suv', t: 'options.vehicles.suv' },
    { v: 'supercar', t: 'options.vehicles.supercar' },
    { v: 'classic car', t: 'options.vehicles.classicCar' },
    { v: 'bus', t: 'options.vehicles.bus' },
    { v: 'train', t: 'options.vehicles.train' },
    { v: 'tank', t: 'options.vehicles.tank' },
    // Air
    { v: 'helicopter', t: 'options.vehicles.helicopter' },
    { v: 'airplane', t: 'options.vehicles.airplane' },
    // Sea
    { v: 'yacht', t: 'options.vehicles.yacht' },
    // Sci-Fi
    { v: 'spaceship', t: 'options.vehicles.spaceship' },
    { v: 'mecha', t: 'options.vehicles.mecha' },
];

export const PET_OPTIONS = [
    { v: '', t: 'options.pets.none' },
    { v: '__random__', t: 'options.pets.random' },
    { v: 'dog', t: 'options.pets.dog' },
    { v: 'cat', t: 'options.pets.cat' },
    { v: 'puppy', t: 'options.pets.puppy' },
    { v: 'kitten', t: 'options.pets.kitten' },
];

export const COLORS_ARR = ['black', 'white', 'grey', 'red', 'blue', 'green', 'yellow', 'purple', 'pink', 'orange', 'brown', 'navy', 'beige', 'olive', 'cyan', 'magenta'];
export const VIVID_COLORS_ARR = ['red', 'blue', 'green', 'yellow', 'purple', 'pink', 'orange', 'cyan', 'magenta', 'lime'];
export const FINISHES_ARR = ['matte', 'glossy', 'sheer', 'opaque', 'satin', 'wet-look', 'metallic'];
export const OPAQUE_DENIERS = ['80 denier', '100 denier', '120 denier', '200 denier'];
export const SHEER_DENIERS = ['15 denier', '20 denier', '30 denier', '40 denier'];
export const PATTERNS_ARR = ['polka dot', 'striped', 'checkered', 'argyle', 'floral', 'lace', 'fishnet', 'geometric', 'animal print'];

export const LETTERING_OPTIONS_ARR = [
    '"love"',
    '"hate"',
    '"dream"',
    '"rebel"',
    '"angel"',
    '"danger"',
    '"sweet"',
    '"kiss"',
    '"meow"',
    'repeating logo',
    'brand name pattern',
    'gothic lettering',
    'script lettering',
    'newspaper print',
    'binary code pattern',
    'barcode pattern',
    '"carpe diem"',
    '"do not cross"',
    '"fragile"',
    'zodiac sign pattern'
];

export const LEGWEAR_PICKER_COLORS = [
    'black', 'charcoal', 'grey', 'silver', 'white', 'ivory', 'beige', 'brown', 
    'red', 'burgundy', 'orange', 'gold', 'yellow', 'olive', 'green', 'mint green', 
    'teal', 'cyan', 'sky blue', 'blue', 'dodger blue', 'navy', 'purple', 'lavender', 'pink',
    'light pink', 'hot pink', 'deep pink', 'pale violet red', 'medium violet red',
    'light salmon', 'salmon', 'dark salmon', 'light coral', 'indian red', 'crimson',
    'firebrick', 'dark red', 'orange red', 'tomato', 'coral', 'dark orange',
    'light yellow', 'lemon chiffon', 'light goldenrod yellow', 'papaya whip', 'moccasin',
    'peach puff', 'pale goldenrod', 'khaki', 'dark khaki', 'cornsilk', 'blanched almond',
    'bisque', 'navajo white', 'wheat', 'burlywood', 'tan', 'rosy brown', 'sandy brown',
    'goldenrod', 'dark goldenrod', 'peru', 'chocolate', 'saddle brown', 'sienna',
    'maroon', 'dark olive green', 'olive drab', 'yellow green', 'lime green', 'lime',
    'lawn green', 'chartreuse', 'green yellow', 'spring green', 'medium spring green',
    'light green', 'pale green', 'dark sea green', 'medium sea green', 'sea green',
    'forest green', 'dark green', 'medium aquamarine', 'light cyan', 'pale turquoise',
    'aquamarine', 'turquoise', 'medium turquoise', 'dark turquoise', 'light sea green',
    'cadet blue', 'dark cyan', 'light steel blue', 'powder blue', 'light blue',
    'light sky blue', 'deep sky blue', 'cornflower blue', 'steel blue', 'royal blue',
    'medium blue', 'dark blue', 'midnight blue', 'thistle', 'plum', 'fuchsia'
];

export const COLOR_NAME_TO_HEX_MAP: Record<string, string> = {
    black: '#000000', white: '#FFFFFF', grey: '#808080', red: '#FF0000', blue: '#0000FF',
    green: '#008000', yellow: '#FFFF00', purple: '#800080', pink: '#FFC0CB', orange: '#FFA500',
    brown: '#A52A2A', navy: '#000080', beige: '#F5F5DC', cyan: '#00FFFF',
    charcoal: '#36454F',
    silver: '#C0C0C0',
    ivory: '#FFFFF0',
    burgundy: '#800020',
    gold: '#FFD700',
    olive: '#808000',
    'mint green': '#98FB98',
    teal: '#008080',
    'sky blue': '#87CEEB',
    'dodger blue': '#1E90FF',
    lavender: '#E6E6FA',
    'light pink': '#FFB6C1',
    'hot pink': '#FF69B4',
    'deep pink': '#FF1493',
    'pale violet red': '#DB7093',
    'medium violet red': '#C71585',
    'light salmon': '#FFA07A',
    salmon: '#FA8072',
    'dark salmon': '#E9967A',
    'light coral': '#F08080',
    'indian red': '#CD5C5C',
    crimson: '#DC143C',
    firebrick: '#B22222',
    'dark red': '#8B0000',
    'orange red': '#FF4500',
    tomato: '#FF6347',
    coral: '#FF7F50',
    'dark orange': '#FF8C00',
    'light yellow': '#FFFFE0',
    'lemon chiffon': '#FFFACD',
    'light goldenrod yellow': '#FAFAD2',
    'papaya whip': '#FFEFD5',
    moccasin: '#FFE4B5',
    'peach puff': '#FFDAB9',
    'pale goldenrod': '#EEE8AA',
    khaki: '#F0E68C',
    'dark khaki': '#BDB76B',
    cornsilk: '#FFF8DC',
    'blanched almond': '#FFEBCD',
    bisque: '#FFE4C4',
    'navajo white': '#FFDEAD',
    wheat: '#F5DEB3',
    burlywood: '#DEB887',
    tan: '#D2B48C',
    'rosy brown': '#BC8F8F',
    'sandy brown': '#F4A460',
    goldenrod: '#DAA520',
    'dark goldenrod': '#B8860B',
    peru: '#CD853F',
    chocolate: '#D2691E',
    'saddle brown': '#8B4513',
    sienna: '#A0522D',
    maroon: '#800000',
    'dark olive green': '#556B2F',
    'olive drab': '#6B8E23',
    'yellow green': '#9ACD32',
    'lime green': '#32CD32',
    lime: '#00FF00',
    'lawn green': '#7CFC00',
    chartreuse: '#7FFF00',
    'green yellow': '#ADFF2F',
    'spring green': '#00FF7F',
    'medium spring green': '#00FA9A',
    'light green': '#90EE90',
    'pale green': '#98FB98',
    'dark sea green': '#8FBC8F',
    'medium sea green': '#3CB371',
    'sea green': '#2E8B57',
    'forest green': '#228B22',
    'dark green': '#006400',
    'medium aquamarine': '#66CDAA',
    'light cyan': '#E0FFFF',
    'pale turquoise': '#AFEEEE',
    aquamarine: '#7FFFD4',
    turquoise: '#40E0D0',
    'medium turquoise': '#48D1CC',
    'dark turquoise': '#00CED1',
    'light sea green': '#20B2AA',
    'cadet blue': '#5F9EA0',
    'dark cyan': '#008B8B',
    'light steel blue': '#B0C4DE',
    'powder blue': '#B0E0E6',
    'light blue': '#ADD8E6',
    'light sky blue': '#87CEFA',
    'deep sky blue': '#00BFFF',
    'cornflower blue': '#6495ED',
    'steel blue': '#4682B4',
    'royal blue': '#4169E1',
    'medium blue': '#0000CD',
    'dark blue': '#00008B',
    'midnight blue': '#191970',
    thistle: '#D8BFD8',
    plum: '#DDA0DD',
    fuchsia: '#FF00FF',
};

export const STYLE_PROMPT_MAP: Record<string, string> = {
    figure: 'plastic toy figure, miniature, on a simple stand, f/11, detailed',
    webtoon: 'webtoon style, clean lines, vibrant colors, cell shading, dramatic panel',
    comic_color: 'american comic book style, bold outlines, dot shading (Ben-Day dots), dynamic action',
    comic_bw: 'japanese manga style, black and white, screentones, sharp lines, speed lines',
    '3d': '3d render, octane render, unreal engine, hyperrealistic, cinematic lighting',
    semi_realistic: 'semi-realistic, illustration, 2.5d, detailed, painterly, beautiful detailed face',
    miniature: 'diorama, miniature scene, tilt-shift photography, shallow depth of field',
    bust_shot: 'bust shot portrait, head and shoulders, studio lighting, plain background',
    lenticular: 'lenticular print effect, 3d effect, holographic',
    fashion: 'cover of a fictional high-fashion magazine, editorial photography, elegant typography',
    movie_poster: 'movie poster, cinematic, epic, title text, credit block',
    gigantic: 'gigantic woman, low angle shot, looking down at the city, kaiju movie style',
    '3d_model': '3d model sheet, character reference sheet, t-pose, multiple angles',
    big_head: "Create a masterful photorealistic caricature by dramatically enlarging the subject's head. CRITICAL: The connection to the body must look natural. To achieve this, subtly reshape the neck and shoulders to plausibly support the enlarged head, ensuring a seamless anatomical blend. Skin texture and lighting must remain consistent. The rest of the body, clothing, pose, and background must remain unchanged. The result should be a high-quality, believable photo manipulation.",
    anthropomorphize: 'anthropomorphic character (gijinka), human-like features and outfit',
    snapshot: 'candid snapshot, point-and-shoot film camera, harsh flash, motion blur, film grain, unposed',
    selfie: 'selfie, taken with a smartphone, arm\'s length shot, slightly high angle, casual expression',
};

export const STYLE_REGENERATION_PROMPTS: Record<string, string> = {
    ...STYLE_PROMPT_MAP,
    figure: "Redraw the image to look like a high-quality, detailed plastic toy figure or garage kit. The subject should be presented as a miniature collectible on a simple stand. The final image needs to have photorealistic details and a sharp focus, as if it were a studio photograph shot with an f/11 aperture.",
    webtoon: "Transform the image into a panel from a modern webtoon. Use clean lines, vibrant cell shading, and a dramatic composition.",
    comic_color: "Re-imagine the image as a page from a classic American color comic book. Employ bold ink outlines and Ben-Day dot patterns for shading.",
    comic_bw: "Convert the image into a black and white manga panel. Use sharp ink lines, screentones for shading, and add dynamic speed lines.",
    '3d': "Render the image as a hyperrealistic 3D scene from a video game cutscene. Use cinematic lighting and textures, as if made in Unreal Engine or Octane.",
    semi_realistic: "Redraw the image in a semi-realistic, 2.5D illustration style. It should have a painterly feel, blending realistic features with an artistic, anime-inspired interpretation, but avoiding flat cell shading or pure photorealism.",
    miniature: "Recreate the scene as a miniature diorama. Apply a tilt-shift effect to create a shallow depth of field, making the subject look like a small model.",
    bust_shot: "Reframe the image as a bust shot portrait. Focus on the head and shoulders with professional studio lighting against a simple, clean background.",
    lenticular: "Apply a 3D lenticular effect to the image, making it appear to shift and have depth as if it were a holographic card.",
    fashion: "Re-envision the image as the cover of a fictional high-fashion magazine. Use editorial lighting, a professional pose, elegant typography for the magazine title, and a high-fashion aesthetic.",
    movie_poster: "Turn the image into a cinematic movie poster. Give it an epic feel, and optionally add space for a title and credit block.",
    gigantic: "Redraw the scene with the subject as a gigantic figure, towering over a city or landscape. Use a low-angle shot to emphasize their scale, like in a kaiju film.",
    '3d_model': "Generate a 3D character model sheet based on the subject. Show the character in a neutral T-pose from multiple angles (front, side, back) on a plain background.",
    big_head: "Create a masterful photorealistic caricature by dramatically enlarging the subject's head. CRITICAL: The connection to the body must look natural. To achieve this, subtly reshape the neck and shoulders to plausibly support the enlarged head, ensuring a seamless anatomical blend. Skin texture and lighting must remain consistent. The rest of the body, clothing, pose, and background must remain unchanged. The result should be a high-quality, believable photo manipulation.",
    anthropomorphize: "Analyze the input image to identify the main subject (animal, object, etc.). Redraw the subject as an anthropomorphic character (gijinka). It should have human-like features, expressions, and posture, while retaining key visual elements of the original subject. The character should be wearing a stylish outfit that creatively incorporates the original subject's colors and patterns.",
    snapshot: "Redraw the image to look like a candid, spontaneous snapshot taken with a cheap point-and-shoot film camera from the 90s. The lighting should be harsh and direct, as if from an on-camera flash, creating strong shadows and blown-out highlights. Introduce a subtle motion blur and noticeable film grain. The composition should feel unposed and authentic, like a found photograph.",
    selfie: "Redraw the image as if it were a selfie. The perspective should be from a smartphone held at arm's length, resulting in a slightly high angle and subtle wide-angle lens distortion. Make the pose and expression look natural and candid for a self-portrait.",
};

export const RANDOM_POSES = [
    // Standing
    'standing gracefully',
    'standing with hands on hips',
    'standing with arms crossed',
    'standing with a confident pose',
    'looking over shoulder with a smile',
    'adjusting glasses',
    'leaning against a wall',
    'dynamic fashion pose',
    'contrapposto pose',
    
    // Walking / Running
    'walking towards the camera',
    'striding purposefully',
    'catwalk strut',
    'running through a field',
    'action pose, sprinting',
    'leaping into the air',
    'mid-stride, captured in motion',
    
    // Sitting
    'sitting on a bench',
    'sitting cross-legged on the floor',
    'sitting on a staircase',
    'perched on a stool',
    'reclining on a sofa',
    'kneeling on one knee',
    'sitting at a desk, looking at camera',
    
    // Lying down
    'lying on the grass, looking up at the sky',
    'lying on a bed, reading a book',
    'reclining on a beach towel',
    
    // Action / Dynamic
    'dancing gracefully',
    'spinning in a circle',
    'dynamic kicking pose',
    'martial arts stance',
    'jumping for joy',
    'heroic landing pose',
    
    // Expressive / Emotional
    'laughing heartily',
    'thoughtful expression, hand on chin',
    'waving at the camera',
    'blowing a kiss',
    'shielding eyes from the sun',
    'pointing towards the camera',
    'a shy glance',
    'looking up at the sky, filled with wonder',
    'crouching down to look at something small',
    
    // Interacting with environment/props
    'holding a coffee cup',
    'reading a book intently',
    'typing on a futuristic keyboard',
    'playing a violin',
    'holding an umbrella in the rain',
    'opening a door',
    'looking through a telescope',
];